server:
  port: 9381
spring:
  application:
    name: zax
  datasource:
    url: jdbc:mysql://rm-wz988oqn7627g91t3so.mysql.rds.aliyuncs.com:3306/zax?useSSL=true&&serverTimezone=GMT%2b8&charset=utf8mb4&parseTime=true&loc=Local
    username: zax
    password: 7788uJmki*
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 100
      auto-commit: true
      idle-timeout: 600000
      connection-timeout: 30000
      leak-detection-threshold: 60000
      pool-name: Zax
      connection-test-query: SELECT 1
mybatis:
  mapper-locations: classpath:mappers/*.xml
  config-location: classpath:mybatis-config.xml
logging:
  config: classpath:logback.xml